spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      name:  twitter-to-kafka-service,config-client
      username: spring_cloud_user
      password: /XNKe7j7//VEeXMhGd/TsHhzuIkm1qXnAV/H7BNI5Fwq7aOuAuPNCvJImDGv/kpJ
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}